apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: snapshot-kibana
spec:
  version: 7.14.0
  count: 1
  elasticsearchRef:
    name: snapshot-elasticsearch

--

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  labels:
    elasticsearch.k8s.elastic.co/node-role: kibana
  name: snapshot-kibana
  namespace: swj1
spec:
  config:
    data: null
  count: 1
  elasticsearchRef:
    name: snapshot-kibana
  enterpriseSearchRef: {}
  http:
    service:
      metadata: {}
      spec:
        ports:
          - name: kibana
            port: 5601
            protocol: TCP
            targetPort: 5601
        type: NodePort
    tls:
      certificate: {}
  image: 172.30.120.59/elastic.m.daocloud.io/kibana/kibana:7.16.3
  monitoring:
    logs: {}
    metrics: {}
  podTemplate:
    metadata:
      creationTimestamp: null
      labels:
        foo: bar
    spec:
      containers:
        - name: kibana
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
  version: 7.16.3
