apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: istio-kibana
  namespace: istio-demo
spec:
  version: 7.14.0
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      automountServiceAccountToken: true
  elasticsearchRef:
    name: istio-elasticsearch
