apiVersion: v1
kind: Service
metadata:
  labels:
    elasticsearch.k8s.elastic.co/cluster-name: mes01
  name: mes01-es-master-0-transport
spec:
  ports:
  - name: tls-transport
    nodePort: 30003
    port: 30003
    protocol: TCP
    targetPort: 30003
  publishNotReadyAddresses: true
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: mes01
    elasticsearch.k8s.elastic.co/statefulset-name: mes01-es-master-78
    statefulset.kubernetes.io/pod-name: mes01-es-master-78-0
  sessionAffinity: None
  type: NodePort