apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    eck.k8s.elastic.co/orchestration-hints: '{"no_transient_settings":true,"service_accounts":false}'
    elasticsearch.k8s.elastic.co/cluster-uuid: 0i9jCXrqR5mBXDZxKUYARQ
    input: '{"cluster":"mcamel-test","namespace":"es-test","name":"es001","describe":"ES
      集群测试（勿删）","version":"7.16.3","service_type":1,"ports":[{}],"node_sets":[{"node_type":1,"replicas":3,"cpu_request":"0.5","cpu_limit":"1","memory_request":"1GB","memory_limit":"1GB","storage_class_name":"hwameistor-storage-lvm-hdd","storage_capacity":"1GB"},{"node_type":2,"replicas":1,"cpu_request":"0.1","cpu_limit":"1","memory_request":"0.1GB","memory_limit":"1GB"},{"node_type":3,"replicas":3,"cpu_request":"0.1","cpu_limit":"1","memory_request":"0.1GB","memory_limit":"1GB","storage_class_name":"hwameistor-storage-lvm-hdd","storage_capacity":"1GB"}],"elasticsearch_password":"YfOaRH0esnly8nGng26POw==","kibanaPorts":[{}],"kibana_service_type":1}'
    shadow.clusterpedia.io/cluster-name: mcamel-test
  generation: 3
  name: es001
  namespace: es-test
spec:
  auth: {}
  http:
    service:
      metadata: {}
      spec:
        ports:
        - name: https
          port: 9200
          protocol: TCP
          targetPort: 9200
        type: NodePort
    tls:
      certificate: {}
  image: elastic.m.daocloud.io/elasticsearch/elasticsearch:7.16.3
  monitoring:
    logs: {}
    metrics: {}
  nodeSets:
  - config:
      node.roles:
      - data
      - ingest
      - ml
    count: 3
    name: data
    podTemplate:
      metadata:
        creationTimestamp: null
        labels:
          elasticsearch.k8s.elastic.co/node-role: data
      spec:
        containers:
        - command:
          - /bin/sh
          - -cxe
          - ulimit -HSn 65535 && /bin/tini -- /usr/local/bin/docker-entrypoint.sh
            eswrapper
          name: elasticsearch
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          securityContext:
            capabilities:
              add:
              - SYS_RESOURCE
        initContainers:
        - command:
          - sh
          - -c
          - sysctl -w vm.max_map_count=262144
          name: sysctl
          resources: {}
          securityContext:
            privileged: true
            runAsUser: 0
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: hwameistor-storage-lvm-hdd
      status: {}
  - config:
      node.roles:
      - master
    count: 3
    name: master
    podTemplate:
      metadata:
        creationTimestamp: null
        labels:
          elasticsearch.k8s.elastic.co/node-role: master
      spec:
        containers:
        - command:
          - /bin/sh
          - -cxe
          - ulimit -HSn 65535 && /bin/tini -- /usr/local/bin/docker-entrypoint.sh
            eswrapper
          name: elasticsearch
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 107374182400m
          securityContext:
            capabilities:
              add:
              - SYS_RESOURCE
        initContainers:
        - command:
          - sh
          - -c
          - sysctl -w vm.max_map_count=262144
          name: sysctl
          resources: {}
          securityContext:
            privileged: true
            runAsUser: 0
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: hwameistor-storage-lvm-hdd
      status: {}
  transport:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
  updateStrategy:
    changeBudget: {}
  version: 7.16.3